apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-1odp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-1odp
    app.kubernetes.io/part-of: tkwch-fix-0075-0050-app
  name: devfile-sample-1odp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-1odp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-1odp
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0050-tenant/tkwch-fix-0075-0050-app/devfile-sample-1odp@sha256:bad34b562465a954fe7c330c5ca3f861ef5283e6995e4251253b4b603d1e72bd
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
